### ISSUE TITLE
Crash on wizard

### ISSUE THREAD

**Issue by msavazzi** [lezhkin11/mvvm-wizard#5]
Following the example I've added a Window with the Wizard and created 1 user control with just a grid and a text in it.
Added it to the Wizard the editor gives me an error on an exception and when I run it I get: 
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MvvmWizard
  StackTrace:
   at MvvmWizard.Controls.Wizard.<TransitTo>d__61.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MvvmWizard.Controls.Wizard.<TryTransitTo>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TitoDoc2020.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

I'm using the NuGet package.
Can you help?

**Comment by lezhkin11** [comment]
Hello,
Could you provide your xaml code and what you have actually done. Callstack above doesn't have any useful information.
And when does this error happen?

**Comment by msavazzi** [comment]
@lezhkin11 thank you will try it again and give you the source

**Comment by mansofta** [comment]
Great works, thank you very much!.
But I have the same problem. I have placed the MVVM Wizard code directly on my project. The project can be compiled and run without error, but in design view the dialog show the stack error.

My code here:

> <Window x:Class="M247TypeA.CirculationWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:controls="clr-namespace:M247TypeA.Components.MvvmWizard.Controls"
        xmlns:local="clr-namespace:M247TypeA.View"
        mc:Ignorable="d"
        Title="CheckIn" Height="500" Width="800"
        >
    <Window.Resources>
        <ResourceDictionary Source="pack://application:,,,/Components/MvvmWizard/Themes/Generic.xaml" />
    </Window.Resources>
    <Grid>
        <controls:Wizard FinishCommand="{Binding CloseCommand}" SharedContext="{Binding SharedContext}">
            <controls:Wizard.Resources>
                <Style TargetType="controls:WizardStep" BasedOn="{StaticResource {x:Type controls:WizardStep}}">
                    <Setter Property="SkipButtonVisibility" Value="Collapsed" />
                </Style>
            </controls:Wizard.Resources>

            <controls:WizardStep x:Name="Step1" ViewType="{x:Type local:CirculationStep1View}" BackButtonVisibility="Collapsed" />
            <controls:WizardStep x:Name="Step2" ViewType="{x:Type local:CirculationStep2View}" />
            <controls:WizardStep x:Name="Step3" ViewType="{x:Type local:CirculationStep3View}" />
            <controls:WizardStep x:Name="Step4" ViewType="{x:Type local:CirculationStep4View}" ForwardButtonTitle="Finish" />

        </controls:Wizard>
    </Grid>
</Window>


And the error in design view

 at M247TypeA.Components.MvvmWizard.Controls.Wizard.<TransitTo>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at M247TypeA.Components.MvvmWizard.Controls.Wizard.<TryTransitTo>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lezhkin11** [comment]
Hey,
I assume you haven't set `ViewResolver` (set it before MainWindow is loaded)
example with unity. You need to tell wizard how to create instance of your view by its type.
`WizardSettings.Instance.ViewResolver = viewType => unityContainer.Resolve(viewType);`

or basic view resolver (Also, you can use reflection)
```
WizardSettings.Instance.ViewResolver = viewType =>
{
   if (viewType == typeof(CirculationStep1View))
   {
      return new CirculationStep1View();
   }

   if (viewType == typeof(CirculationStep2View}))
   {
      return new CirculationStep2View}();
   }

   // and others

   throw new InvalidOperationException("Unknown view");
};
```

I've change exception to something more helpful -> version `1.1.2`

Regarding the designer - this probaby will not work if you use DI containers for view resolver.

**Comment by mansofta** [comment]
I worked around hours and found that is not the problem of view resolver. That error occurred when I implement some code inside  Public override Task OnTransitedTo(TransitionContext transitionContext) of the first wizardstep.  
I start a new task for that then it seem be ok.
